fb-clone:
  email-sender: noreply@fbclone.com

aws:
  access-key: ENC(RgZI3wpIVdZYtrGfwlfAyxQPSCaLNE+aUSDkz6oERZgZEiJrhotWVae2huC+i4CGywzKagZUSw2fArbHtiVpHw==)
  secret-key: ENC(FdLY5VGBsM5tnyEObTh/Rrgu2m7c4pqPYDEDGs98dh6QpLDloZLO+uHIU/HUw/Ao27tQO+kUMrKVbJ/qAIy5dfl8fsouGBjoWB2JxHB7/2I=)
  region: 'us-east-2'
  bucket: 'fb-clone'

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ENC(nq8MnaNwF3a0Czb3V+0mB1+CSdN713dpemkiCWAddf1Z2XHjdiEV/pvSCPfKpbYW)
    password: ENC(O0gcyY+u65Z/TG9iPdHMjAJ3oxHHUldOZyVQr/tzqGzsebjKl4jEFCv748D7VQwy)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/fb_clone
    username: 'root'
    password: 'P@ssw0rd'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB